### ISSUE TITLE
Item clear if player dies

### ISSUE THREAD

**Issue by imDaniX** [Bastian/SafeTrade#11]
If player will be killed while trading, all items in trade window will be deleted forever.
They're not dropping or something. Just R.I.P.

**Comment by BtoBastian** [comment]
Are you using the latest versions?
Items should be dropped on the ground if one of the players dies while trading.

**Comment by imDaniX** [comment]
Version 1.0.14. Maybe it's because of PaperSpigot? If it is - no problems to you.
