### ISSUE TITLE
SafeTrade new translation: messages_hu (Hungarian)

### ISSUE THREAD

**Issue by montlikadani** [Bastian/SafeTrade#19]
Welcome!
**I would like to add a new language to your plugin (if not, not). Language name: hu_HU (Hungarian).**
For the file: ANSI encoding (to write accented letters to chat, if you want to rewrite it: copy it and paste it again)

Download: http://www.mediafire.com/file/apobi3jp3go9ibc/Messages_hu+%28SafeTrade%29.properties
Or: https://pastebin.com/SkGqLpbg

**Comment by BtoBastian** [comment]
Thank you :)
I'll add it in the next release of the plugin!
